"""create_tables

Revision ID: 09c58444af2b
Revises: 
Create Date: 2024-06-27 17:53:45.709962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c58444af2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('mer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Integer(), nullable=True),
    sa.Column('sell_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mer_id')
    )
    op.create_table('sell',
    sa.Column('sell_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('sell_sum', sa.Integer(), nullable=True),
    sa.Column('gain_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sell_id')
    )
    op.create_table('sell_detail',
    sa.Column('sell_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sell_id', sa.Integer(), nullable=True),
    sa.Column('mer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sell_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sell_detail')
    op.drop_table('sell')
    op.drop_table('merchants')
    # ### end Alembic commands ###
